trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: ATRAssessment
      type: git
      name: /Github/acruzsua/ATRAssessment
      ref: ref/heads/main

stages:
  - stage: api_tests
    displayName: "API Regression Tests"
    jobs:
      - template: ./template.tests.cypress.run.sequential.yml
          TestVariables:
            TestRootPath: $(Build.SourcesDirectory)/$(Build.Repository.Name)/cypress_api_fw